
KAFKA_HOST: ${KF_HOST}
ZOOKEPER_HOST: ${ZKPR_HOST}
POSTGRES_USER: ${PG_USER}
POSTGRES_PASSWORD: ${PG_PASSWORD}
POSTGRES_URL: ${PG_URL}
#LOGSTASH_HOST: prodelk.keepz.me:5000

PAYMENT_URI: ${PAYMENT_SERVICE_URI:http://payment-service.prod.svc.cluster.local:8060}


REALM: sweeft
KEYCLOAK_HOST: ${KC_HOST}
KEYCLOAK_ADMIN_USER: ${KC_ADMIN_USER}
KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
KEYCLOAK_CLIENT: ${KC_CLIENT}
KEYCLOAK_SECRET: ${KC_SECRET}
KEYCLOAK_INTERNAL_SERVICE_CLIENT_ID: ${KC_INTERNAL_SERVICE_CLIENT_ID:sweeft-internal-service}
KEYCLOAK_INTERNAL_SERVICE_CLIENT_SECRET: ${KC_INTERNAL_SERVICE_CLIENT_SECRET:2914d4ab-266e-4449-b913-b33203e3a326}
MOBILE_KEYCLOAK_CLIENT: sweeft-api-gateway-mobile
MOBILE_KEYCLOAK_SECRET: 564c9666-840e-4b2f-9b35-29fbae4ddd19
WEB_KEYCLOAK_CLIENT: sweeft-api-gateway-web
WEB_KEYCLOAK_SECRET: 6237fc76-0c36-40f0-a9a1-7a3dfaa5ad98
KEYCLOAK_REDIRECT_URI: https://www.keepz.me/otp

REDIS_HOST: ${RDS_HOST}
ELASTIC_HOST: ${ES_HOST}
ELASTIC_URI: ${ES_URI}
ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
EUREKA_HOST: ${EURK_HOST}
SERVER_HOST: ${SRV_HOST}
SDA_URL: https://sda.keepz.me/send

LIMIT_HOST: https://app.keepz.me:9000

TINY_URL_TOKEN: ${TINY_URL_TKN}
TINY_URL_URL: https://api.tinyurl.com/create
TINY_DOMAIN: tiny.keepz.me
DOMAIN: app.keepz.me

USER_GROUP_URL: ${PAYMENT_SERVICE_URI}/api/v1/user-account/{userId}/userGroup

MERCHANT_REGISTRATION_CAMPAIGN_MSG_ENABLE: true
USER_REGISTRATION_CAMPAIGN_MSG_ENABLE: true

FRAUD_ANALYZER_URI: ${FRAUD_ANALYZER_SERVICE_URI}/api/v1/action
FRAUD_ANALYZER_ACTIVATED: true

IDENTOMAT_COMPANY_KEY: 6580b40d299edf612f00bf72_bf48a50e59ab4a065075485aaaf77dfb927daba2
IDENTOMAT_BASE_URL: https://widget.identomat.com/external-api/
IDENTOMAT_EXTERNAL_BASE_URL: https://external.api.identomat.com/
URL_BASE: https://app.keepz.me/pay
